### ISSUE TITLE
Upgrade autoprefixer from 1.1 to 5.1

### ISSUE THREAD

**Issue by paazmaya** [esundahl/metalsmith-autoprefixer#1]
https://github.com/postcss/autoprefixer/releases

**Comment by gustavnikolaj** [comment]
I made a release to npm (https://www.npmjs.com/package/metalsmith-autoprefixer-gustavnikolaj) of my PR referenced above which has these changes which can be used until @esundahl merges this or fixes the problems in another way :-)
