### ISSUE TITLE
Autoprefixer not working

### ISSUE THREAD

**Issue by arunnan** [esundahl/metalsmith-autoprefixer#11]
Hi,
The given below is my build.js file. I need to add autoprefixer to my code. kindly help.

require("harmonize")(["harmony-generators"]);
var Metalsmith  = require('metalsmith'),
    jade        = require('metalsmith-jade'),
    sass        = require('metalsmith-sass'),
    autoprefixer = require('metalsmith-autoprefixer'),
    watch        = require('metalsmith-watch');

Metalsmith(__dirname)
    .destination('./build')  
    .use(jade({
        pretty: true
    }))
    .use(sass({
        outputStyle: "expanded"
    }))
    .use(autoprefixer());
    .use(watch({
      paths: {
        "${source}/**/*": true,
        "templates/**/_": "__/_.jade",
      },
      livereload: true,
    }))
    .build(function(err, files) {
        if (err) { throw err; }
    });

**Comment by edwardessing** [comment]
Not working for me either...I think it might have something to do with using metalsmith-sass...
