### ISSUE TITLE
process() method is deprecated

### ISSUE THREAD

**Issue by michel-kraemer** [esundahl/metalsmith-autoprefixer#7]
When I run the plugin it says

```
Autoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead
```

I've used this plugin before, but this message seems new to me. Any help is appreciated.

Thanks,
Michel

**Comment by slwen** [comment]
@michel-kraemer Same issue here, just put up a PR which solves this issue.

**Comment by jamenlyndon** [comment]
Awesome fix Sam, hope to see it merged soon.

**Comment by michel-kraemer** [comment]
@slwen Thanks for the PR!
